spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    template:
      default-topic: library-events
    producer:
# multiple broker server
#     bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
        
---
spring:
  config:
    activate:
      on-profile: nonprod
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9095,localhost:9096
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      ssl:
        trust-store-location: file:D:\Learning\Udemy\apache-kafka-for-developers-using-springboot\ssl\client.truststore.jks
        trust-store-password: gaurav
        key-store-location: file:D:\Learning\Udemy\apache-kafka-for-developers-using-springboot\ssl\client.keystore.jks
        key-store-password: gaurav
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithm:

---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    producer:
      bootstrap-servers: prod:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
